VehicleTypes = {
    ["normal"] = {
        scripts = {
			"Base.Van",
			"Base.StepVan",
			"Base.VanAmbulance",
			"Base.StepVanAirportCatering",
			"Base.StepVanMail",
			"Base.StepVan_Blacksmith",
			"Base.StepVan_Butchers",
			"Base.StepVan_Cereal",
			"Base.StepVan_Citr8",
			"Base.StepVan_Florist",
			"Base.StepVan_Genuine_Beer",
			"Base.StepVan_Glass",
			"Base.StepVan_LouisvilleSWAT",
			"Base.StepVan_Masonry",
			"Base.StepVan_MobileLibrary",
			"Base.StepVan_SmartKut",
			"Base.StepVan_CompleteRepairShop",
			"Base.StepVan_HuangsLaundry",
			"Base.StepVan_Jorgensen",
			"Base.StepVan_Heralds",
			"Base.StepVan_LouisvilleMotorShop",
			"Base.StepVan_MarineBites",
			"Base.StepVan_Mechanic",
			"Base.StepVan_Plonkies",
			"Base.StepVan_RandisPlants",
			"Base.StepVan_Scarlet",
			"Base.StepVan_SouthEasternHosp",
			"Base.StepVan_SouthEasternPaint",
			"Base.StepVan_USL",
			"Base.StepVan_Zippee",
			"Base.VanRadio",
			"Base.VanRadio_3N",
			"Base.VanBrewsterHarbin",
			"Base.Van_BugWipers",
			"Base.VanBuilder",
			"Base.VanCarpenter",
			"Base.VanCoastToCoast",
			"Base.VanDeerValley",
			"Base.VanBeckmans",
			"Base.VanFossoil",
			"Base.VanGreenes",
			"Base.VanMail",
			"Base.VanOvoFarm",
			"Base.Van_Blacksmith",
			"Base.Van_Charlemange_Beer",
			"Base.Van_CraftSupplies",
			"Base.Van_Glass",
			"Base.Van_HeritageTailors",
			"Base.Van_Leather",
			"Base.Van_Locksmith",
			"Base.Van_Masonry",
			"Base.Van_Perfick_Potato",
			"Base.VanGardenGods",
			"Base.VanGardener",
			"Base.VanJohnMcCoy",
			"Base.VanJonesFabrication",
			"Base.VanKerrHomes",
			"Base.VanKnobCreekGas",
			"Base.Van_KnoxDisti",
			"Base.VanKnoxCom",
			"Base.VanKorshunovs",
			"Base.Van_LectroMax",
			"Base.VanLouisvilleLandscaping",
			"Base.Van_MassGenFac",
			"Base.VanMccoy",
			"Base.VanMechanic",
			"Base.VanMeltingPointMetal",
			"Base.VanMetalheads",
			"Base.VanMetalworker",
			"Base.VanMicheles",
			"Base.VanMobileMechanics",
			"Base.VanMooreMechanics",
			"Base.VanOldMill",
			"Base.VanPennSHam",
			"Base.VanPlattAuto",
			"Base.VanPluggedInElectrics",
			"Base.VanRiversideFabrication",
			"Base.VanRosewoodworking",
			"Base.VanSchwabSheetMetal",
			"Base.VanSpiffo",
			"Base.Van_Transit",
			"Base.VanTreyBaines",
			"Base.VanUncloggers",
			"Base.VanUtility",
			"Base.Van_VoltMojo",
			"Base.VanWPCarpentry",
			"Base.VanSeats_Space",
			"Base.VanSeats_LadyDelighter",
			"Base.VanSeats_Trippy",
			"Base.VanSeats_Valkyrie",
			"Base.86fordE150",
			"Base.86fordE150dnd",
			"Base.86fordE150long",
			"Base.86fordE150mm",
			"Base.86fordE150pd",
			"Base.86fordE150slide",
			"Base.86fordE150slideSpiffo",
			"Base.86fordE150so",
			"Base.86fordE150ksp",
			"Base.86fordE150med",
			"Base.86fordE150mccoy",
			"Base.86fordE150longW",
			"Base.86fordE150LVairportShuttle",
			"Base.86fordE150LBMWradio",
			"Base.86fordE150leatherwork",
			"Base.86fordE150brewster",
			"Base.86fordE150deerValley",
			"Base.86fordE150fossoil",
			"Base.86fordE150locksmith",
			"Base.86fordE150knobCreek",
			"Base.86fordE150knoxDistilery",
			"Base.86fordE150korshunovs",
			"Base.86fordE150lvLandscaping",
			"Base.86fordE150metalheads",
			"Base.86fordE150michelesWoodshop",
			"Base.86fordE150mobileMechanics",
			"Base.86fordE150oldMillWaterCompany",
			"Base.86fordE150blacksmith",
			"Base.86fordE150pluggedInElectrics",
			"Base.86fordE150postal",
			"Base.86fordE150riversideFab",
			"Base.86fordE150rosewoodWorking",
			"Base.86fordE150schwab",
			"Base.86fordE150stoneworksMasonry",
			"Base.86fordE150tasteTheBrew",
			"Base.86fordE150voltMojo",
			"Base.86fordE150wpCarpentry",
			"Base.86fordE150beckmansBuilding",
			"Base.86fordE150brushAndClay",
			"Base.86fordE150bugWipers",
			"Base.86fordE150ccconstruction",
			"Base.86fordE150greenes",
			"Base.86fordE150jones",
			"Base.86fordE150kerrHomes",
			"Base.86fordE150knoxTelecom",
			"Base.86fordE150kyTransit",
			"Base.86fordE150lectromax",
			"Base.86fordE150massGenfac",
			"Base.86fordE150McCoyWoodworking",
			"Base.86fordE150meltingPointMetal",
			"Base.86fordE150mooresMechanics",
			"Base.86fordE150oVoFarms",
			"Base.86fordE150pennSham",
			"Base.86fordE150perfick",
			"Base.86fordE150plattAutoRepair",
			"Base.86fordE150theGardenGods",
			"Base.86fordE150treyBaines",
			"Base.86fordE150uncloggers",
			"Base.86fordE150zenith",
			"Base.86fordE150heritageTailors",
			"Base.86fordE150creatureCruiser",
			"Base.86fordE150theLadyDelighter",
			"Base.86fordE150quantumVessel",
			"Base.86fordE150valkyriesSpear",
			"Base.86fordE150mesmerWagon",
			"Base.87fordF700bank",
			"Base.87fordF700swat",
			"Base.90fordF350SWAT",
			"Base.90fordF350ambulance",
			"Base.TrailerKI5cargoLarge",
			"Base.80f350ambulanceFEMAas",
			"Base.CadillacRangerSWATFBSP",
			"Base.stepvanchevyFBIBOMBSQUAD",
			"Base.stepvanchevybOMBSQUAD",
			"Base.Vehicles_fematruck01",
			"Base.moveurselfFBIEVIDENCERT",
			"Base.VanJester",
			"Base.1979rastrojeroFlete",
			"Base.1990renaultTrafic",
			"Base.1990renaultTraficATC",
			"Base.1990renaultTraficAmarillo",
			"Base.1990renaultTraficAmbulancia",
			"Base.1990renaultTraficLechero",
			"Base.1990renaultTraficNegro",
			"Base.1990renaultTraficPasajeros",
			"Base.1990renaultTraficRojo",
			"Base.1990renaultTraficVerde",
			"Base.BasicVan",
			"Base.StepVanIceCreamFreeze",
			"Base.Van_Azumanga",
			"Base.USPSTruck",
			"Base.VanMysteryMachine",
			"Base.Van_Melonero",
			"Base.Van_Tapicero",
			"Base.Van_afiladoras",
			"Base.aMOOzonVan",
			"Base.uaz2206",
			"Base.uaz2208",
			"Base.VanATeam",
			"Base.VanLBK",
			"Base.80f350ambulance",
			"Base.86econoline",
			"Base.86econolineambulance",
			"Base.86econolineflorist",
			"Base.Trailer_fr_moving_medium",
			"Base.fr_ch_astro_92",
			"Base.fr_ch_stepvan_80",
			"Base.fr_ch_stepvan_80_police",
			"Base.fr_do_ram_90_moving",
			"Base.fr_fo_econoline_86",
			"Base.fr_fo_econoline_86_ambulance",
			"Base.fr_fo_econoline_86_florist",
			"Base.fr_fo_f350_ambulance_80",
			"Base.pzkChevalierVan70",
			"Base.pzkContinentalGuardian",
			"Base.pzkContinentalGuardianLlama",
			"Base.pzkContinentalGuardianService",
			"Base.pzkDashVan70",
			"Base.pzkDashVan70Riddle",
			"Base.pzkF350BoxAmbulance",
			"Base.pzkF350BoxCUCV",
			"Base.pzkF350BoxSwat",
			"Base.pzkF350BoxUmoveit",
			"Base.pzkFranklinBankTruck",
			"Base.pzkFranklinSwatTruckLouisvilleSWAT",
			"Base.pzkFranklinTruckGarbage",
			"Base.pzkFranklinVan70",
			"Base.pzkStepVanFedLog",
			"Base.pzkStepVanHotDog",
			"Base.pzkStepVanIceCream",
			"Base.pzkStepVanMilk",
			"Base.pzkStepVanPizza",
			"Base.pzkStepVanSwatLouisvilleSWAT",
			"Base.pzkStepVanTacoVan",
			"Base.pzkStepVanUPZ",
			"Base.pzkVanBox",
			"Base.pzkVanBoxAmbulance",
			"Base.pzkVanBoxFiretruck",
			"Base.pzkVanBoxSwat",
			"Base.pzkVanCamper",
			"Base.pzkVanGigamart",
			"Base.pzkVanMcCoy",
			"Base.pzkVanMultivan",
			"Base.pzkVanMultivanPayday",
			"Base.pzkVanPoliceLouisvillePD",
			"Base.pzkVanPoliceMeadeSheriff",
			"Base.pzkVanPoliceWestPoint",
			"Base.pzkVanSeatsTaxi",
			"Base.pzkVanZSquad",
			"Base.pzkVanilaVanAmbulance",
			"Base.ww_fo_cseries_box",
			"Base.ww_sb_zipvan",
			"Base.Trailer_ww_50senclosed",
			"Base.84ramvan",
			"Base.84ramvanutility",
			"Base.87gmcarmouredcar",
			"Base.87gmcc7000ambulance",
			"Base.87macktruckswat",
			"Base.93FL70swat",
			"Base.93G10KnoxDisti",
			"Base.93G10Scarlet",
			"Base.93G10fossoil",
			"Base.93G10massgenfacvo",
			"Base.93G10van",
			"Base.93G10vanlectromax",
			"Base.93c10boxambulance",
			"Base.93c10vanambulance",
			"Base.93c10vanshort",
			"Base.93c10vanshortlectromax",
			"Base.93vandura",
			"Base.93vanduraKnoxDisti",
			"Base.93vanduraScarlet",
			"Base.93vandurafossoil",
			"Base.93vanduramassgenfacvo",
			"Base.93vandurashort",
			"Base.93vandurashortspiffo",
			"Base.93vanduraspiffo",
			"Base.fhq92Econoline",
			"Base.fhq92Econoline4Door",
			"Base.fhq92EconolineAmbulance",
			"Base.fhq92EconolineAmbulanceLightbar",
			"Base.fhq92EconolinePAYDAY",
			"Base.fhq92EconolinePanel",
			"Base.fhq92EconolineT3Ambulance",
			"Base.fhq92EconolineValkyrie",
			"Base.fhq92EconolineXL",
			"Base.fhq92EconolineXLPanel",
			"Base.fhqVWT2T1",
			"Base.fhqVWT2T1Livery",
			"Base.fhqVWT2T1Van",
			"Base.80f350ambulanceFEMAas",
			"Base.80f350ambulancelagrangelivery",
			"Base.86econolinePDOCpt",
			"Base.ww_sb_zipvan_bluefox",
			"Base.pzkGrummanLLVMail",
			"Base.pzkFVanKendo",
			"Base.97bushAmbulance",
			"Base.97bushmaster",
			"Base.StepVan_UPZ",
			"Base.Vodnik",
			"Base.Ammoguns",
			"Base.Bakkhoneta",
			"Base.CRMtruck",
			"Base.Chemolli",
			"Base.Ditoseadio",
			"Base.Joker86Racing",
			"Base.Mordineta",
			"Base.Paramedic",
			"Base.Roblevan",
			"Base.Rockvan",
			"Base.Shindenvan",
			"Base.Spiffoneta",
			"Base.Swatvan",
			"Base.TMNTVan",
			"Base.TodoCaserito",
			"Base.TurnoZero",
			"Base.M113_APC",
			"Base.M113_Police",
			"Base.M163",
			"Base.85chevyStepVan",
			"Base.85chevyStepVanButchers",
			"Base.85chevyStepVanLibrary",
			"Base.85chevyStepVanPropane",
			"Base.85chevyStepVanFlorist",
			"Base.85chevyStepVanMasonry",
			"Base.85chevyStepVanBlacksmith",
			"Base.85chevyStepVanSeHospitality",
			"Base.85chevyStepVanDelirosPlonkies",
			"Base.85chevyStepVanTheCompleteRepair",
			"Base.85chevyStepVanSePaintingServices",
			"Base.85chevyStepVanLvAirportCatering",
			"Base.85chevyStepVanPostal",
			"Base.85chevyStepVanUsLogistics",
			"Base.85chevyStepVanMarineBites",
			"Base.85chevyStepVanRandys",
			"Base.85chevyStepVanLvMotorshop",
			"Base.85chevyStepVanGenuine",
			"Base.85chevyStepVanHerald",
			"Base.85chevyStepVanScarletOak",
			"Base.85chevyStepVanJorgensen",
			"Base.85chevyStepVanSmartCut",
			"Base.85chevyStepVanTimelessGlass",
			"Base.85chevyStepVanZippeeMarket",
			"Base.85chevyStepVanCitrusWave",
			"Base.85chevyStepVanMrHuangsLaundry",
			"Base.85chevyStepVanSunBallz",
			"Base.ww_fo_cseries_police_1"
        },
        rooms = (function()
            local t = {}
            for col = 0, 37 do table.insert(t, { x = col * 60 + 22560, y = 12060, z = 0 }) end
            return t
        end)(),
        offset = { x = 1, y = 1 },
        requiresSeat = false,
        requiresTrunk = true,
        trunkParts = {
            TrunkDoor = true, DoorRear = true, DoorRearLeft = true, DoorRearRight = true
        },
		genX = 0,
		genY = 0,
		genFloor = 1,
		roomWidth = 2,
		roomHeight = 3
    },
    ["bus"] = {
        scripts = {
			"Base.87fordB700military",
			"Base.87fordB700prison",
			"Base.87fordB700school",
			"Base.ATAArmyBus",
			"Base.ATAPrisonBus",
			"Base.ATASchoolBus",
			"Base.ATAApocalypseBus",
			"Base.fr_fo_b700_prisonlong",
			"Base.fr_fo_b700_schoollong",
			"Base.fr_fo_b700_schoolshort",
			"Base.fr_gm_newlook_70_35foot",
			"Base.pzkFranklinTruckBus",
			"Base.pzkFranklinTruckBusAirport",
			"Base.pzkFranklinTruckBusArmy",
			"Base.pzkFranklinTruckBusPrison",
			"Base.pzkTransitBus",
			"Base.caio",
			"Base.87rtsbus",
			"Base.87rtsbusshort",
			"Base.93D60HF2",
			"Base.93D60HFlow",
			"Base.93D60HFmod",
			"Base.fhqB10M",
			"Base.fhqB10M_Riv",
			"Base.pucara",
			"Base.pzkGmNewLookBus"
        },
        rooms = (function()
            local t = {}
            for col = 0, 37 do table.insert(t, { x = col * 60 + 22560, y = 12120, z = 0 }) end
            return t
        end)(),
        offset = { x = 1, y = 1 },
        requiresSeat = true,
        requiresTrunk = false,
		genX = 0,
		genY = 0,
		genFloor = 1,
		roomWidth = 3,
		roomHeight = 7
    },
    ["small"] = {
        scripts = {
			"Base.86chevyM1010",
			"Base.86chevyM1031",
			"Base.63Type2Van",
			"Base.63Type2VanHippie",
			"Base.63Type2VanApocalypse",
			"Base.63Type2VanMilitary",
			"Base.86oshkoshFRTR55",
			"Base.86oshkoshKYFD",
			"Base.86oshkoshUSMC",
			"Base.90pierceArrow",
			"Base.1992fiatFiorino",
			"Base.1992fiatFiorinoArcor",
			"Base.1992fiatFiorinoPan",
			"Base.1979rastrojeroCarni",
			"Base.fr_gr_llv_89",
			"Base.fr_pi_engine_90_fire",
			"Base.pzkFireTruckFlatLadder",
			"Base.pzkFireTruckFlatPumper",
			"Base.pzkFranklinTruckFire",
			"Base.pzkMinivan2",
			"Base.pzkMinivanC22",
			"Base.pzkMinivanChev",
			"Base.pzkMinivanConvoy",
			"Base.pzkMinivanMPV",
			"Base.pzkMinivanPrev",
			"Base.pzkMinivanStellaris",
			"Base.pzkMinivanStellarisMail",
			"Base.pzkMinivanStellarisTaxi",
			"Base.pzkMinivanT3",
			"Base.pzkMinivanT3C",
			"Base.pzkMinivanTask",
			"Base.89defender90",
			"Base.89defender90utility",
			"Base.89defender110",
			"Base.89defender110utility",
			"Base.92gmcserriacovered",
			"Base.93arrow",
			"Base.93frieghtlinerlfiretruck",
			"Base.93lefrance",
			"Base.93lefrance2",
			"Base.93lefranceladder",
			"Base.firepumperLagrangeFD",
			"Base.firepumperballardsFD",
			"Base.ww_fo_cseries_firetruck",
			"Base.ww_mack_nseries_firetruck",
			"Base.pzkCadillacGageRangerPolice",
			"Base.pzkCadillacGageRangerArmy",
			"Base.andresmicra",
			"Base.M41_Walker_Bulldog",
			"Base.ww_fo_cseries_firetruck_longcab",
			"Base.ww_m_nseries_firetruck",
			"Base.ww_m_nseries_firetruck_longcab",
			"Base.ww_my_cseries_firetruck",
			"Base.ww_my_cseries_firetruck_longcab"
        },
        rooms = (function()
            local t = {}
            for col = 0, 37 do table.insert(t, { x = col * 60 + 22560, y = 12180, z = 0 }) end
            return t
        end)(),
        offset = { x = 1, y = 1 },
        requiresSeat = true,
        requiresTrunk = false,
		genX = 0,
		genY = 0,
		genFloor = 1,
		roomWidth = 2,
		roomHeight = 2
    },
    ["3x2caravan"] = {
        scripts = {
			"Base.TrailerHome",
			"Base.TrailerHomeExplorer",
			"Base.TrailerHomeHartman",
			"Base.ATA_VanDeRumba",
			"Base.1990renaultTraficCamper",
			"Base.Trailer_fr_camper_scamp",
			"Base.pzkTrailerCamping",
			"Base.ATA_VanDeRumbaGardenia",
			"base.ATA_VanDeRumbaEyeSky",
			"Base.ATA_VanDeRumbaMS",
			"Base.ATA_VanDeRumbaLittleLiuDuck"
        },
        rooms = (function()
            local t = {}
            for col = 0, 37 do table.insert(t, { x = col * 60 + 22560, y = 12240, z = 0 }) end
            return t
        end)(),
        offset = { x = 1, y = 1 },
        requiresSeat = true,
        requiresTrunk = false,
		genX = 0,
		genY = 0,
		genFloor = 1,
		roomWidth = 3,
		roomHeight = 2
    },
    ["3x6caravan"] = {
        scripts = {
			"Base.UnimogTrailer",
			"Base.86bounder",
			"Base.86econolinerv",
			"Base.73Winnebago",
			"Base.fr_fl_bounder_86",
			"Base.fr_fo_econoline_rv_86",
			"Base.pzkFranklinTruckRV",
			"Base.pzkBounder86",
			"Base.pzkChieftain73",
			"Base.FleetwoodLab",
			"Base.Trailerpart22"
        },
        rooms = (function()
            local t = {}
            for col = 0, 37 do table.insert(t, { x = col * 60 + 22560, y = 12300, z = 0 }) end
            return t
        end)(),
        offset = { x = 2, y = 2 },
        requiresSeat = true,
        requiresTrunk = false,
		genX = 0,
		genY = 0,
		genFloor = 1,
		roomWidth = 3,
		roomHeight = 6
    },
    ["3x7empty"] = {
        scripts = {
			"Base.87fordF700box",
			"Base.SemiTruckBox",
			"Base.86bounderHAzardmaterials",
			"Base.86econolinervFBIMHQLG",
			"Base.86econolinervLVMHQLG",
			"Base.f700boxbombsquadLG",
			"Base.Vehicles_sogmobilehq",
			"Base.SpecialdivisionsTruckFlg",
			"Base.SpecialdivisionsTruckFlg2",
			"Base.Trailer_fr_moving_large",
			"Base.fr_fo_f700_90_boxlarge",
			"Base.fr_fo_f700_90_boxmed",
			"Base.fr_is_nrr_93_boxmed",
			"Base.isoContainer2",
			"Base.isoContainer4",
			"Base.f700boxArmysurplus",
			"Base.f700boxLGElouisvilleelectric",
			"Base.f700boxShinrapilas",
			"Base.f700boxTisconstruction",
			"Base.f700boxVHSTRUCKas",
			"Base.f700boxVKYFOODSas",
			"Base.f700boxbombsquadLG",
			"Base.f700boxenergypilas",
			"Base.f700boxlouisvillelogistics",
			"Base.f700boxnaranjita",
			"Base.f700boxshellFedEXas",
			"Base.f700boxshellSYSCOas",
			"Base.f700boxshellUPSas",
			"Base.f700boxshellautozoneas",
			"Base.f700boxshellbestbuyas",
			"Base.f700boxsouthpetrol",
			"Base.pzkFranklinTruckBox",
			"Base.pzkFranklinTruckBoxLectromax",
			"Base.ww_f_superfreighter",
			"Base.ww_f_superfreighter_citr8",
			"Base.ww_f_superfreighter_construction",
			"Base.ww_f_superfreighter_lawn",
			"Base.ww_f_superfreighter_library",
			"Base.ww_f_superfreighter_mechanics",
			"Base.ww_f_superfreighter_military",
			"Base.ww_f_superfreighter_police",
			"Base.87macktruckbox",
			"Base.88W900swat",
			"Base.88w900firedept",
			"Base.89FLC112boxtruck",
			"Base.93fl70box",
			"Base.93frieghtlignerambulance",
			"Base.93frieghtlignerambulancefire",
			"Base.ww_fo_cseries_box_electronics",
			"Base.ww_fo_cseries_box_glass",
			"Base.ww_fo_cseries_box_plonkies",
			"Base.ww_fo_cseries_box_spiffos",
			"Base.ww_fo_cseries_box_zippemart",
			"Base.Tatrapan",
			"Base.TatrapanAmbulance",
			"Base.TatrapanApocalypto"
        },
        rooms = (function()
            local t = {}
            for col = 0, 37 do table.insert(t, { x = col * 60 + 22560, y = 12360, z = 0 }) end
            return t
        end)(),
        offset = { x = 1, y = 1 },
        requiresSeat = false,
        requiresTrunk = true,
        trunkParts = {
            TrunkDoor = true, DoorRear = true, DoorRearLeft = true, DoorRearRight = true,
            TrunkDoor1 = true, TrailerTrunk = true, TrailerTrunk1 = true, TrailerTrunk2 = true,
            TrailerTrunk3 = true, BigTrunk = true, BigTrunk1 = true, BigTrunk2 = true,
            BigTrunk3 = true, SmallTrunk = true, SmallTrunk1 = true, SmallTrunk2 = true,
            SmallTrunk3 = true, VanSeatsTrunk2 = true, NormalTrunk = true, NormalTrunk1 = true,
            NormalTrunk2 = true, NormalTrunk3 = true, TruckBed = true, AnimalEntry = true,
            TrailerAnimalFood = true, ATSMegaTrunk = true, TrailerAnimalEggs = true
        },
		genX = 0,
		genY = 0,
		genFloor = 1,
		roomWidth = 3,
		roomHeight = 7
    },
    ["4x12colossal"] = {
        scripts = {
			"Base.SemiTrailerVan",
			"Base.Trailer_fr_semi_container",
			"Base.Trailer_fr_semi_van",
			"Base.TrailerTSMega",
			"Base.TrailerTSMegaAnimal",
			"Base.SemiTrailerVanCattle",
			"Base.ArmoredMotorhome",
			"Base.88navistarbox",
			"Base.88navistarboxknoxdistillery",
			"Base.88navistarboxlectromax",
			"Base.88navistarboxmail",
			"Base.88navistarboxspiffo",
			"Base.88w900",
			"Base.88w900fossoil",
			"Base.88w900massgenfacvo",
			"Base.88w900scarletdist"
        },
        rooms = (function()
            local t = {}
            for col = 0, 37 do table.insert(t, { x = col * 60 + 22560, y = 12420, z = 0 }) end
            return t
        end)(),
        offset = { x = 1, y = 1 },
        requiresSeat = false,
        requiresTrunk = true,
        trunkParts = {
            TrailerTrunk = true, BigTrunk = true, NormalTrunk = true,
            TrunkDoor = true, DoorRear = true, DoorRearLeft = true, DoorRearRight = true,
            TrunkDoor1 = true, TrailerTrunk = true, TrailerTrunk1 = true, TrailerTrunk2 = true,
            TrailerTrunk3 = true, BigTrunk = true, BigTrunk1 = true, BigTrunk2 = true,
            BigTrunk3 = true, SmallTrunk = true, SmallTrunk1 = true, SmallTrunk2 = true,
            SmallTrunk3 = true, VanSeatsTrunk2 = true, NormalTrunk = true, NormalTrunk1 = true,
            NormalTrunk2 = true, NormalTrunk3 = true, TruckBed = true, AnimalEntry = true,
            TrailerAnimalFood = true, ATSMegaTrunk = true, TrailerAnimalEggs = true
        },
		genX = 0,
		genY = 0,
		genFloor = 1,
		roomWidth = 4,
		roomHeight = 12
    }
}
intOffset = {
    2,
	0.000002288818359375,
	0.000001071673525377229
}
function Act()
    local aM = getActivatedMods()
	return aM
end
return {
    VehicleTypes = VehicleTypes,
    check = Act(),
	intOffset = intOffset
}
